### ISSUE TITLE
Video player's replay button does not work on Android 4.4 (KitKat)

### ISSUE THREAD

**Issue by robinmanuelthiel** [Thepagedot/IRMGARD#7]
When using Android 4.4 (KitKat), the replay button of the video player does not work.

**Comment by einRobby** [comment]
Seems to be just an Emulator problem. #HuffDev

**Comment by frankwende** [comment]
This doesn't work on Android **4.2** also.
**Fix**: Re-navigate to VideoActivity for devices running on Android prior to **Lollipop**.
